"""url_model_update

Revision ID: 4694593c6580
Revises: e36919271595
Create Date: 2022-05-31 13:13:58.724427

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4694593c6580'
down_revision = 'e36919271595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('URL_map', 'short',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('URL_map', 'short',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
